### ISSUE TITLE
Too many errors

### ISSUE THREAD

**Issue by grainw** [periakiva/finding_berries#1]
Thank you for your contribution, but there are too many mistakes, I can not run this project, are you still improving this project?

**Comment by periakiva** [comment]
Can you specify what errors you are getting? On my end I am able to compile the docker container and run the code without an issue (tried on Ubuntu 18.04, GTX 1080). The data released is currently in raw format (full image, unlabelled), but it will be released with annotations in the future. However, the code should work with any data for the task.

Edit:
Closing for now since there is no followup.
